# Generated by Django 5.2.6 on 2025-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_color', models.CharField(max_length=5)),
                ('car_model', models.CharField(max_length=10)),
                ('car_no', models.IntegerField()),
                ('car_quality', models.CharField(max_length=30)),
            ],
        ),
    ]
